### ISSUE TITLE
Versions for dependencies

### ISSUE THREAD

**Issue by reynoldscem** [ML-GSAI/MicroDreamer#1]
Hi, you include a few third party libraries with instructions to clone them separately. Could you please specify at what commit hash or tag you're using them?

Alternatively, if you add them as submodules this can be tracked in the repo itself.

**Comment by TRL-0** [comment]
Thank you! We have updated the README.txt and added the version of some third party libraries we used.

**Comment by reynoldscem** [comment]
Thank you!
